### ISSUE TITLE
I get an array to string conversion error on save

### ISSUE THREAD

**Issue by matthewswallace** [optimistdigital/nova-table-field#1]
When I try to create or update I get an error saying that it's an Array to String conversion error. What type does the column in the DB need to be. I've tried both jsonb and text

**Comment by matthewswallace** [comment]
```
public function fields(Request $request)
    {
        return [
            BelongsTo::make('Product'),
            Text::make('Title'),
            Table::make('Spec Table')
        ];
    }
    ```
![Screen Shot 2021-02-26 at 3 35 13 PM](https://user-images.githubusercontent.com/123816/109357808-71f82b80-7848-11eb-82a7-b79171cc68cf.png)
![Screen Shot 2021-02-26 at 3 35 21 PM](https://user-images.githubusercontent.com/123816/109357810-71f82b80-7848-11eb-9146-304728be9b80.png)

**Comment by Tarpsvo** [comment]
Hi! Try casting the 'spec_table' to 'array' in your model. Ie `protected $casts = ['spec_table' => 'array']`.

**Comment by matthewswallace** [comment]
That worked! Thank you. 

It may be a good idea to put that in the documentation :)
